name: Rakuten France Multimodal Product Data Classification
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - zipfile

  # Extra requirements
  # - tensorflow-gpu
  # - pytorch
  # - keras
  # - lightgbm

  - pip
  - pip:
    - ramp-workflow
    - ramp-utils


#     Extra requirements pip
#     - xgboost
#     - catboost